#!/usr/bin/env python

# Copyright (C) <2015> EMBL-European Bioinformatics Institute

# This program is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of
# the License, or (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.

# Neither the institution name nor the name 2015_summer_school
# can be used to endorse or promote products derived from
# this software without prior written permission.
# For written permission, please contact <marco@ebi.ac.uk>.

# Products derived from this software may not be called 2015_summer_school
# nor may 2015_summer_school appear in their names without prior written
# permission of the developers. You should have received a copy
# of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.

import sys
import vcf

if len(sys.argv) < 4:
    sys.stderr.write('USAGE: correct_vcf VCF START OUT\n')
    sys.exit(65)

infile, start, out = sys.argv[1:4]
start = int(start)

i = vcf.Reader(open(infile))
o = vcf.Writer(open(out, 'w'), i)
for r in i:
    r.POS += start
    o.write_record(r)
